### ISSUE TITLE
Simplification

### ISSUE THREAD

**Issue by ahoarau** [LouisCharlesC/safe#11]
In the spirit of simplifying everything, I would challenge the following points: 
- The real use of the doxygen file : I dont think anyone using this lib would build it and run it. They'd rather open the readme on the website. 
- The use of gmock+gtest vs headeronly libs (catch2+fakeit) --> Using header-only libs would make the travis simpler and the project **self-contained**
- Have an `examples` folder with real-world cases : tests are hard to read, simple tests add code to compile.
- Are tests really necessary in this repo ? 
- Can we remove everything and just keep safe headers + readme (and put the tests in a different repos) ? That would increase readability++. 

Please comment this :)

**Comment by LouisCharlesC** [comment]
1. Ok, it seems that github and travis have facilities to automatically publish doxygen documentation anyways, see https://gist.github.com/bmegli/e22ba525dda0b197b2d4440d08f43ae2 for instance. Maybe we should look into this.
2. No specific opinion (see item 5).
3. Sure, gimme your code :)
4. The tests I've written are useful for me. Are they for anyone else ? Probably not.
5. yeah, that's a good idea. Then item 2 becomes a non-issue.

**Comment by LouisCharlesC** [comment]
Regarding item 5, would examples be kept in safe repo, or in safe-tests repo ?

**Comment by ahoarau** [comment]
Maybe in the safe repo yes. Law 9: Some things cannot be simplified :+1:
