### ISSUE TITLE
Some questions about library

### ISSUE THREAD

**Issue by prsolucoes** [LouisCharlesC/safe#12]
Hi,

I have some questions:

- This library work on raspberry pi (armv7)?
- This library work on iOS (x86, x86_64, armv8, armv8e)?
- This library work on Android (x86, x86_64, armv7, arm64)?
- It support iterator? I want use with `std::map<std::string, MyStruct>` and `std::map<std::string, MyClass>`.

Thanks.

**Comment by ahoarau** [comment]
The library has only libstdc++ as dependency. So I'm guessing it is portable everywhere.

> It support iterator? I want use with std::map<std::string, MyStruct> and std::map<std::string, MyClass>.

Safe can protect any class/type.

**Comment by prsolucoes** [comment]
I made a sample with that but appear don't work:
https://github.com/LouisCharlesC/safe/issues/13

Can you help me pls?

**Comment by LouisCharlesC** [comment]
Answer in issue issue #13.
Don't hesitate to reopen if needed.
