### ISSUE TITLE
Do not use unnamed namespace in header

### ISSUE THREAD

**Issue by travnick** [LouisCharlesC/safe#16]
https://github.com/LouisCharlesC/safe/blob/faebc6c2f45c2b568bc83926b33386d3f7aacd35/include/safe/safe.h#L21

reason: https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL59-CPP.+Do+not+define+an+unnamed+namespace+in+a+header+file

**Comment by LouisCharlesC** [comment]
Uh oh. Thanks for the tip!
I'm working on and off on a huge commit that will pretty much touch every line of code in this repo. This fix will be included in there!

**Comment by LouisCharlesC** [comment]
There, you have it! Thanks again for the input.

**Comment by travnick** [comment]
I'm happy to help!
