### ISSUE TITLE
Naming scheme nitpicking: letter case

### ISSUE THREAD

**Issue by eyalroz** [LouisCharlesC/safe#19]
Most commonly-used C++ libraries, AFAIK - including, of course, the standard library - use `this_kind_of_names`, not camel case (`ThisKindOfNames`). Consider switching.  `safe::access_traits::is_read_only` seems nicer.

**Comment by LouisCharlesC** [comment]
I absolutely agree, I do prefer snake_case. But I was used to CamelCase when I started coding this and it stayed like that.

I did have a version in snake_case once, but I threw it away. I didn't like the idea of changing each and every name only for a matter of taste for lower/upper case and underscores.

Maybe if a few people ask I'll do it, who knows.

**Comment by eyalroz** [comment]
This would go along nicely with issue #20 ...

**Comment by LouisCharlesC** [comment]
#20 includes this one.
