### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by werdahias** [LouisCharlesC/safe#24]
In readme.md it states:
"Most cmake code comes from this repo: https://github.com/bsamseth/cpp-project and Craig Scott's CppCon 2019 talk: Deep CMake for Library Authors. Many thanks to the authors!"
Is this just autogenerated from there? Or is there actual code by third parties?
I need to know that because I am packaging safe for debian and the copyright needs to be strict.

**Comment by LouisCharlesC** [comment]
Hey, I don't know enough about copyrights to even know if I answer your question. Please tell me if I somehow miss the point or need to give you more information.

It's been a long time and I do not remember exactly what I did, but looking at the code it seems that:
- I got at least a whole file ([cmake/DocTarget.cmake](https://github.com/LouisCharlesC/safe/blob/master/cmake/DocTarget.cmake)) taken directly from [cpp-project](https://github.com/bsamseth/cpp-project). Some other files I adapted. This project is under [the Unlicense](https://github.com/bsamseth/cpp-project/blob/master/LICENSE).
- I wrote most of [cmake/InstallTarget.cmake](https://github.com/LouisCharlesC/safe/blob/master/cmake/InstallTarget.cmake) based on info from [Craig Scott's talk](https://www.youtube.com/watch?v=m0DwB4OvDXk).

**Comment by CountOmega** [comment]
Ok, thanks for the insight. So InstallTarget.cmake is just based on the talk, but not copied from there, right? What about safeconfig.cmake.in? 

> * Some other files I adapted.

Any other ones? Sorry for all the scrutiny but the copyright has to be accurate

**Comment by LouisCharlesC** [comment]
> So InstallTarget.cmake is just based on the talk, but not copied from there, right? 

I'll have to ask what exactly is meant by "copying" ? Do I have to remember if I copy/pasted the thing or if I wrote an exact copy looking at the slides ? Most code in the slides is about a project "someProj", obviously I had to change that. The talk is filled with small snippets, I guess I assembled them into useful files. That sounds half copying half writing to me :D

> What about safeconfig.cmake.in?

I can't find any trace of this file's content in my usual cmake sources, so maybe I wrote this one. But it's impossible, I don't know cmake well enough to be able to "write some cmake code". It is 100% sure that the content comes from a mix of the two sources I stated, other cmake template projects you can find on github which I forgot about, stackoverflow answers and the cmake documentation.

One thing I remember is that nothing worked at first, so I did have to fiddle a lot with the cmake, probably making it less likely that it was copied.

Just to make it clear: I'm actually trying to give a precise answer, but it's been a long time :(

**Comment by CountOmega** [comment]
Ok thank you for your insight. That should good enough. Copying in this context is 1:1 copying. If you were just "inspired" it's still your code I guess.

**Comment by LouisCharlesC** [comment]
Phew, good!
Out of curiosity, can I ask why you are doing this? I'm not even sure I know what "packaging for debian" really means!
Thanks.

**Comment by LouisCharlesC** [comment]
Cool, thanks for doing this :)

Shall we close this ?

**Comment by CountOmega** [comment]
Once the package gets accepted, sure.

**Comment by werdahias** [comment]
see debian [tracker](https://tracker.debian.org/pkg/safe ) .Closing.
