### ISSUE TITLE
More recent CMake possible?

### ISSUE THREAD

**Issue by offa** [LouisCharlesC/safe#6]
Is it possible to upgrade CMake to a more recent version (v3.x)? This would enable many improvements.

CMake >= 3.12 would make sense, as it's the version shipped on Travis CI.

**Comment by ahoarau** [comment]
You can use any cmake version you want. I'm sure there no problem in upgrading it to whatever version.
It is advised anyway to people to just copy and paste the 2 header files to their own projet anyway :)

**Comment by offa** [comment]
Great, thanks! :smile:
